jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 18.17.0
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.0

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to AWS Amplify
        run: amplify publish
