type Event = {
  name: string;
  src: string;
  branch?: string;
  community?: string;
  category: string;
  type?: string;
  url: string;
};

export const eventList: Event[] = [
  {
    name: "Women in Buisness",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/women-in-business_.png",
    community: "IEDC",
    category: "TECHNICAL",
    type: "EXPO",
    url: "",
  },
  {
    name: "Idea Pitching",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-18_at_22.29.37_c9735fa3.jpg",
    branch: "CSE",
    category: "TECHNICAL",
    type: "COMPETITION",
    url: "https://forms.gle/QkLi6aC2NWWVwB998",
  },
  {
    name: "EV Drive",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-18_at_22.29.13_5f8481ef.jpg",
    branch: "EEE",
    category: "TECHNICAL",
    type: "WORKSHOP",
    url: "https://forms.gle/i5GFyfR9xoziVT8i7",
  },
  {
    name: "Hacknite",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-18_at_22.29.08_791165df.jpg",
    branch: "CSE",
    category: "TECHNICAL",
    type: "COMPETITION",
    url: "https://hacknite.devfolio.co/",
  },
  {
    name: "Technical Quiz",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-18_at_14.33.25_d5a52fd6.jpg",
    branch: "CE",
    category: "TECHNICAL",
    type: "COMPETITION",
    url: "https://forms.gle/s3scptcDW9VxbnCY6",
  },
  {
    name: "E-Football Tournament",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-17_at_23.29.49_1e9e2961.jpg",
    branch: "CSE",
    category: "TECHNICAL",
    type: "COMPETITION",
    url: "https://forms.gle/L9n9FEmNxzUB95n67",
  },
  {
    name: "BGMI Tournament",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-17_at_23.29.38_60d3cb58.jpg",
    branch: "CSE",
    category: "TECHNICAL",
    type: "COMPETITION",
    url: "https://forms.gle/odm8Y8mHyXtLYxSFA",
  },
  {
    name: "Capture The Flag: Cyber Challenge",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-17_at_23.29.25_caaf84b1.jpg",
    community: "IEEE",
    category: "TECHNICAL",
    type: "COMPETITION",
    url: "https://forms.gle/zhCkh8Nt2pA5WfDJ8",
  },
  {
    name: "Tech Talks: Life of an Entrepreneur",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-17_at_23.29.05_52c66f9e.jpg",
    branch: "CSE",
    category: "TECHNICAL",
    type: "TECH-TALK",
    url: "",
  },
  {
    name: "Tech Talks: Cyber Security",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-17_at_23.29.04_0ffb2014.jpg",
    branch: "CSE",
    category: "TECHNICAL",
    type: "TECH-TALK",
    url: "",
  },
  {
    name: "Non Destructive Testing",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-15_at_22.37.09_e6b94974-min.jpg",
    branch: "CE",
    category: "TECHNICAL",
    type: "WORKSHOP",
    url: "https://forms.gle/BTtGLVhjbyoBa9B5A",
  },
  {
    name: "Robo Soccer",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-15_at_22.36.07_69120677-min.jpg",
    branch: "EC",
    category: "TECHNICAL",
    type: "COMPETITION",
    url: "https://forms.gle/DSPwqdXuQ7qLyPX99",
  },
  {
    name: "Da Vinci's Vault",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-15_at_22.32.31_120de47f-min.jpg",
    branch: "ME",
    category: "TECHNICAL",
    type: "COMPETITION",
    url: "https://forms.gle/Jn7rwTLzPwLAqAZ56",
  },
  {
    name: "EV Hack",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-15_at_22.32.30_63b4b103-min.jpg",
    branch: "EEE",
    category: "TECHNICAL",
    type: "COMPETITION",
    url: "https://forms.gle/BjCj72LnXnodi6GJ6",
  },
  {
    name: "Project Expo",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-13_at_22.00.36_d0ea6677-min.jpg",
    branch: "CSE",
    category: "TECHNICAL",
    type: "EXPO",
    url: "https://bit.ly/RegProjectExpo",
  },
  {
    name: "Quake Proof Creation Challenge",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-13_at_22.00.19_9e5926ea-min.jpg",
    branch: "CE",
    category: "TECHNICAL",
    type: "COMPETITION",
    url: "https://forms.gle/9Qh7oi5pXkAdQrfu6",
  },
  {
    name: "Wrenching Wheels",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-13_at_19.31.05_d777ea88-min.jpg",
    branch: "ME",
    category: "TECHNICAL",
    type: "COMPETITION",
    url: "https://forms.gle/X96zHH2Pg6cho8hj7",
  },
  {
    name: "Malhar: Musical Band Competition",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-13_at_19.30.52_89e38456-min.jpg",
    category: "CULTURAL",
    type: "COMPETITION",
    url: "https://docs.google.com/forms/d/e/1FAIpQLScPczdk4WDJgO2SGQFMicLwgQPMnkm4S1Z1DWmSXvuAHYNfjA/viewform",
  },
  {
    name: "iRobotics Workshop",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-20_at_11.49.45_db67373d.jpg",
    branch: "EC",
    category: "TECHNICAL",
    type: "WORKSHOP",
    url: "",
  },
  {
    name: "Build your Dreams",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-20_at_11.49.27_012367d9.jpg",
    branch: "CE",
    category: "TECHNICAL",
    type: "TECH-TALK",
    url: "",
  },
  {
    name: "Clues and Cranks",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-20_at_11.49.22_f2a885d2.jpg",
    branch: "ME",
    category: "TECHNICAL",
    type: "COMPETITION",
    url: "https://forms.gle/vbsFfv9Dt94G8U7h9",
  },
  {
    name: "Designathon",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/designathon.png",
    branch: "CSE",
    category: "TECHNICAL",
    type: "COMPETITION",
    url: "https://designathon24.devfolio.co/",
  },
  {
    name: "Drishti",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/dristi.jpg",
    branch: "BSH",
    category: "TECHNICAL",
    type: "EXPO",
    url: "https://forms.gle/A5483R6CCdL6JMPc6",
  },
  {
    name: "Group Dance Competition: Beat Sync Battle",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/dance-group.png",
    category: "CULTURAL",
    type: "COMPETITION",
    url: "https://forms.gle/zFNAjmtzbAJKvadWA",
  },
  {
    name: "CODE-UNO",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-20_at_22.37.40_3afdb779.jpg",
    branch: "EC",
    category: "TECHNICAL",
    type: "COMPETITION",
    url: "https://surl.li/qsiam",
  },
  {
    name: "Solo Dance Competition: Beat Sync Battle",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-21_at_20.00.10_9c00d390.jpg",
    branch: "ALL",
    category: "CULTURAL",
    type: "ALL EVENTS",
    url: "https://docs.google.com/forms/d/e/1FAIpQLSeKfrzFRR8M8-iZ9Zug8pt_Aue4UEHI77d2beyO7WJFVgzY8g/viewform?usp=sf_link",
  },
  {
    name: "REMAPPED",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-21_at_22.49.47_c420fecb.jpg",
    branch: "ME",
    category: "CULTURAL",
    type: "EXPO",
    url: "",
  },
  {
    name: "Mextalk",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-21_at_22.50.07_0aa40614.jpg",
    branch: "ME",
    category: "TECHNICAL",
    type: "TECH-TALK",
    url: "",
  },
  {
    name: "Belfort of Wallstreet",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/Untitled-2.png",
    branch: "ALL",
    category: "TECHNICAL",
    type: "TECH-TALK",
    url: "https://bellfort-of-wallstreet.netlify.app/",
  },
  {
    name: "Conference - ICICE",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-15_at_22.38.24_507d5af6-min.jpg",
    branch: "CE",
    category: "TECHNICAL",
    type: "TECH-TALK",
    url: "",
  },

];

export const featuredEventList: Event[] = [
  {
    name: "Designathon",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/designathon.png",
    branch: "CSE",
    category: "TECHNICAL",
    type: "COMPETITION",
    url: "https://designathon24.vercel.app",
  },
  {
    name: "Hacknite",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-18_at_22.29.08_791165df.jpg",
    branch: "CSE",
    category: "TECHNICAL",
    type: "COMPETITION",
    url: "https://hacknite.devfolio.co/",
  },
  {
    name: "Belfort of Wallstreet",
    src: "https://dnbca6q7do6n.cloudfront.net/media/techletics24/Untitled-2.png",
    branch: "ALL",
    category: "TECHNICAL",
    type: "TECH-TALK",
    url: "https://bellfort-of-wallstreet.netlify.app/",
  },

];
